openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /balance/add:
    post:
      operationId: addBalance
      responses:
        "200":
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Balance"
        description: Created courier
        required: true
    get:
      operationId: getBalance
      responses:
        "200":
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Balance"
        description: Created courier
        required: true
  /balance/reserve:
    post:
      operationId: reserveBalance
      responses:
        "200":
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BalanceReserve"
        description: Created reserve balance
        required: true
    delete:
      operationId: deleteReserve
      responses:
        "200":
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BalanceReserve"
        description: Created reserve balance
        required: true
    get:
      operationId: getReserve
      responses:
        "200":
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BalanceReserve"
        description: get reserve balance
        required: true
components:
  schemas:
    Balance:
      type: object
      properties:
        user_id:
          type: number
          format: int32
        account:
          type: string
        balance:
          type: number
          format: float
    BalanceReserve:
      type: object
      properties:
        order_id:
          type: string
        user_id:
          type: number
          format: int32
        price:
          type: number
          format: float
        completed:
          type: boolean
